### ISSUE TITLE
Command Manager

### ISSUE THREAD

**Issue by AN2548** [NotGGhost/jSkype#11]
Could you like bring back the command manager/command handler, since I have like no other way of recognising a command, due to the fact you don't have a message received event, as far as I am aware of. Therefore, could you bring it back or could you show me a way to receive commands? Thanks.

**Comment by SpongyBacon** [comment]
There is a message event? https://github.com/NotGGhost/jSkype/blob/master/source/xyz/gghost/jskype/api/events/UserChatEvent.java

To see the other events, don't be afraid to look into the source. https://github.com/NotGGhost/jSkype/tree/master/source/xyz/gghost/jskype/api/events

**Comment by AN2548** [comment]
o lel
Thanks
xd

**Comment by AN2548** [comment]
plus, how did you get <img> tags on your bot?
;-;
.-.
rip
#oppp

**Comment by NotGGhost** [comment]
As stated, events can be found in the "xyz.gghost.jskype.api.events" package (https://github.com/NotGGhost/jSkype/tree/master/source/xyz/gghost/jskype/api/events). The command handler was removed due to the stability and that it favours bot features compared to overall skype functionality.
