### ISSUE TITLE
User is incompatible with GroupUser

### ISSUE THREAD

**Issue by AN2548** [NotGGhost/jSkype#16]
I'm trying to do
```java
for (User user : api.getGroupById(e.getChat().getId()).getClients()){
                api.getGroupById(e.getChat().getId()).kick(user.getUsername());
            }
```
What I'm trying to do is kick everyone in that certain chat, however I don't know how else to do it, except from using that code. There error message is ![error image](https://i.gyazo.com/cedfd309baa5471455e09258da138f2f.png)

And, when I try to change it to ```GroupUser user ```, I get this error message
![error message #2](https://i.gyazo.com/af9687819c64cac6248e26533e241dd3.png)
Yes, I have tried to do
```java 
import xyz.gghost.jskype.internal.user.GroupUser;
```
But, I get the same error as for ```GroupUser user```

Any help would be appreciated.

**Comment by SpongyBacon** [comment]
````for (GroupUser user : api.getGroupById(e.getChat().getId()).getClients()) {
 // your other code
}`````

To get a User from a GroupUser, use `GroupUser#getUser`.

**Comment by NotGGhost** [comment]
Seams like you're trying to make a chat clearer: 
'''
for (GroupUser user : e.getChat().getClients()) {
    e.getChat().kick(user.getUser().getUsername()); 
}
'''
