### ISSUE TITLE
Throw RecaptchaException instead of FailedToLoginException in new system

### ISSUE THREAD

**Issue by SpongyBacon** [NotGGhost/jSkype#21]
Skype's new captcha system throws a FailedToLoginException with a message asking for detail verification instead of throwing the RecaptchException.

Also rename it to CaptchaException as it's no longer using Google's ReCaptcha.

**Comment by NotGGhost** [comment]
Do you have the new error page dump?
I'm currently limited internet wise.

**Comment by SpongyBacon** [comment]
SoonTM

**Comment by SpongyBacon** [comment]
wowok

**Comment by NotGGhost** [comment]
I would but cba

**Comment by SpongyBacon** [comment]
ill do it @ some point

**Comment by NotGGhost** [comment]
k

**Comment by NotGGhost** [comment]
I don't captcha's are as common now as they was before but idk

**Comment by SpongyBacon** [comment]
https://gist.github.com/ed381a0a273c4ecd8e8f

**Comment by SpongyBacon** [comment]
Captchas happen a lot now when the API can't reconnect. It spam reconnects and then gets captcha'd.

**Comment by NotGGhost** [comment]
Captcahs seems easy to crack, but can't be certain. I'll look into them after I'm done with youtube.

**Comment by NotGGhost** [comment]
- Should be fixed.
