### ISSUE TITLE
Editing messages doesn't seem to support formatting

### ISSUE THREAD

**Issue by SpongyBacon** [NotGGhost/jSkype#27]
When trying to add a link into an edited message, the client does not render it. However, when sending a new message, it works.

I think this is an issue with Skype client instead of your API, might want to look over that though.

**Comment by stopbox** [comment]
Skype patched this

**Comment by NotGGhost** [comment]
> Skype patched this

Editing other peoples messages were patched, however formatting wasn't.

Fixed in 3.8.2 (bug fix update just for this)
