### ISSUE TITLE
We need to double-check your details. Please review this page and submit it again.  Process finished with exit code 0

### ISSUE THREAD

**Issue by AN2548** [NotGGhost/jSkype#28]
When I try to login using jSkype, I keep getting this error on startup.
![Error](https://i.gyazo.com/27583f4a081cd4bdb22df788aa3f6d7d.png)

Do you know how to fix it? Any help would be appreciated.

**Comment by SpongyBacon** [comment]
Hey, this is due to a Skype captcha. The system allowing you to enter the answer for the captcha image is nearing completion, however for now try not to relog often & wait a few hours if you do get captcha'd.

If you have a dynamic IP, changing your IP works.

**Comment by NotGGhost** [comment]
3.8.1 should generate the recaptcha exception instead of throwing that. Either way, until we add a captcha resolving system, you'll just have to wait it out or as SpongyBacon said, change your IP.
