### ISSUE TITLE
Internet shortage causing internal dos attack

### ISSUE THREAD

**Issue by SpongyBacon** [NotGGhost/jSkype#32]
So it disconnects, and the attempts to reconnect.
My internet, being fantastic, can't keep up with this.
The API continues to try and reconnect, causing my internet to overload and then enter full retardation mode in which it stops working.

tl;dr ur api ddosed me :((((

**Comment by NotGGhost** [comment]
Still more powerful than LOIC

**Comment by SpongyBacon** [comment]
4th time this has happened today >_>

**Comment by NotGGhost** [comment]
?

**Comment by SpongyBacon** [comment]
(my internet is not enjoying this feature)

**Comment by NotGGhost** [comment]
I'll add something but a 1mbps internet line is the least of my worries atm

**Comment by SpongyBacon** [comment]
It spam reconnects... has the same effect as LOIC >_>

**Comment by NotGGhost** [comment]
lol. The next update is easer on the reconnects
