### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by NotGGhost** [NotGGhost/jSkype#8]
Handle joes internet without crashing

**Comment by SpongyBacon** [comment]
@TalkTalk

**Comment by NotGGhost** [comment]
TalkTalk = BT reseller?
If yes, should have known

**Comment by SpongyBacon** [comment]
ye

copper cables, no speed difference directly from bt in my area, so worth it for the price

**Comment by NotGGhost** [comment]
Don't think this was ever a bug, since the whole block of code is try/catch'd, so you must have stopped it. The skype4web servers can go offline for a few minutes and and the API will remain stable whilst losing only minor functionality. Minor meaning profile moods, custom display names, and thats about it. Other stuff shouldn't NPE.
